name: Test backend

on:
  push:
    branches:
      - backend
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Changing working directory to backend
        working-directory: /apps/backend
      - name: Test
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install
      - run: yarn test
