name: Test backend

on:
  push:
    branches:
      - backend
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        yarn-version: ["3.2.4"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          yarn-version: ${{ matrix.yarn-version }}
      - name: Change working directory
        run: sudo cd ./apps/backend
      - name: Print working directory
        run: pwd
      - name: Run las
        run: ls -al
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
